# Generated by Django 5.0.9 on 2026-09-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("issuer", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("obtained", "Obtenue"), ("in_progress", "En cours")],
                        default="obtained",
                        max_length=20,
                    ),
                ),
                ("date_obtained", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=80)),
                ("credential_url", models.URLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "-date_obtained"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=150)),
                ("organization", models.CharField(max_length=150)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Laisser vide si poste actuel.", null=True),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "headline",
                    models.CharField(
                        help_text="Ligne de statut affichée sous le nom (ex. rôle + spécialités).",
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("summary", models.TextField(help_text="Paragraphe de présentation (profil professionnel).")),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profil",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "summary",
                    models.CharField(help_text="Résumé court affiché sur la carte projet.", max_length=280),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description détaillée (optionnelle)."),
                ),
                (
                    "stack",
                    models.CharField(
                        help_text="Technologies séparées par ' · ' (ex. Kubernetes · Helm · Terraform).",
                        max_length=300,
                    ),
                ),
                ("repo_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["order", "-is_featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cloud_devops", "Cloud & DevOps"),
                            ("linux_scripting", "Linux & Scripting"),
                            ("network_security", "Réseau & Sécurité"),
                            ("development", "Développement"),
                            ("ai_prompting", "IA & Prompting"),
                            ("project_mgmt", "Gestion de projet"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Niveau de maîtrise indicatif, de 1 (notions) à 5 (expert)."
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="portfolio.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point clé d'expérience",
                "verbose_name_plural": "Points clés d'expérience",
                "ordering": ["order"],
            },
        ),
    ]
